# Generated by Django 4.1.2 on 2022-10-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('work_experience', models.TextField(max_length=1000)),
                ('technical_skills', models.TextField(max_length=1000)),
                ('soft_skills', models.TextField(max_length=1000)),
            ],
        ),
    ]
